export interface DepartmentPositions {
  [key: string]: string[];
}

export const departmentPositions: DepartmentPositions = {
  Production: [
    'Producer',
    'Assistant Producer',
    'Production Assistant',
    'Line Producer',
    'Production Coordinator',
    'Production Manager',
    'Script Supervisor',
  ],
  'Assistant Director': [
    'Assistant Director',
    'Second Assistant Director',
    'Third Assistant Director',
    'AD Coordinator',
    'Script Supervisor',
  ],
  Camera: [
    'Camera Operator',
    'Camera Assistant',
    'Director of Photography',
    'Camera Trainee',
    'Focus Puller',
    'Steadicam Operator',
    'B Camera Operator',
  ],
  Lights: [
    'Gaffer',
    'Best Boy Electric',
    'Lighting Technician',
    'Electrician',
    'Lighting Designer',
    'Rigging Electrician',
    'Follow Spot Operator',
  ],
  Grip: [
    'Grip',
    'Key Grip',
    'Best Boy Grip',
    'Dolly Grip',
    'Swing Grip',
    'Rigging Grip',
    'Grip Trainee',
  ],
  Sound: [
    'Sound Mixer',
    'Boom Operator',
    'Sound Assistant',
    'Sound Designer',
    'Foley Artist',
    'Location Sound Recordist',
    'Post-Production Sound Editor',
  ],
  Wardrobe: [
    'Costume Designer',
    'Wardrobe Assistant',
    'Wardrobe Supervisor',
    'Costume Maker',
    'Dresser',
    'Costume Standby',
    'Makeup and Wardrobe Stylist',
  ],
  'Make-up': [
    'Make-up Artist',
    'Hair Stylist',
    'Special Effects Make-up Artist',
    'Prosthetic Make-up Artist',
    'Make-up Assistant',
    'Key Make-up Artist',
  ],
  'Art Department': [
    'Art Director',
    'Set Designer',
    'Props Master',
    'Set Dresser',
    'Art Department Assistant',
    'Prop Assistant',
    'Concept Artist',
    'Set Painter',
  ],
  SFX: [
    'Special Effects Coordinator',
    'SFX Technician',
    'SFX Assistant',
    'Pyrotechnician',
    'SFX Supervisor',
    'Model Maker',
  ],
  Stunts: [
    'Stunt Coordinator',
    'Stunt Performer',
    'Stunt Double',
    'Stunt Rigger',
    'Stunt Driver',
    'Fight Choreographer',
    'Stunt Medic',
  ],
  Transport: [
    'Driver',
    'Transport Coordinator',
    'Transportation Captain',
    'Van Driver',
    'Truck Driver',
    'Transportation Assistant',
  ],
  Basecamp: [
    'Basecamp Coordinator',
    'Basecamp Assistant',
    'Basecamp Manager',
    'Craft Services Assistant',
    'Camp Attendant',
  ],
  Catering: [
    'Catering Manager',
    'Catering Assistant',
    'Chef',
    'Catering Supervisor',
    'Catering Coordinator',
    'Food Truck Operator',
  ],
  Locations: [
    'Location Manager',
    'Location Assistant',
    'Location Scout',
    'Location Coordinator',
    'Location Wrangler',
  ],
  Security: [
    'Security Manager',
    'Security Guard',
    'Head of Security',
    'Set Security Officer',
    'Production Security',
  ],
  Talents: [
    'Talent Manager',
    'Talent Agent',
    'Talent Coordinator',
    'Casting Director',
    'Talent Scout',
    'Talent Booker',
  ],
  Extras: [
    'Extras Coordinator',
    'Extras Assistant',
    'Extras Casting Director',
    'Extras Manager',
    'Extras Stand-in',
  ],
  Others: [
    'Miscellaneous',
    'General Worker',
    'Set Medic',
    'Runner',
    'Production Assistant',
    'Office Assistant',
    'Event Coordinator',
  ],
};
